# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.9.2
  - 2.9.1

branches:
  only:
    - master
script: sh ./travis.sh

notifications:
  email:
    recipients:
      - anton.panasenko@gmail.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
